enum types {
	START_FETCHING_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/START_FETCHING',
	INIT_EDIT_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/INIT',
	END_FETCHING_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/END_FETCHING',
	SET_ELEMENT_STYLE = 'EDIT_TEMPLATE/SET_ELEMENT_STYLE',
	CHANGE_HEADER_STATUS = 'EDIT_TEMPLATE/HEADER/CHANGE_HEADER_STATUS',
	CHANGE_FOOTER_STATUS = 'EDIT_TEMPLATE/HEADER/CHANGE_FOOTER_STATUS',
	CHANGE_LAYOUT = 'EDIT_TEMPLATE/BODY/CHANGE_LAYOUT',
}

export default types
