const CHANGE_HEADER_STYLE = 'EDIT_TEMPLATE/HEADER/CHANGE_STYLE';
const ENABLE_DISABLE_HEADER = 'EDIT_TEMPLATE/HEADER/ENABLE_DISABLE';
const CHANGE_FOOTER_STYLE = 'EDIT_TEMPLATE/FOOTER/CHANGE_STYLE';
const ENABLE_DISABLE_FOOTER = 'EDIT_TEMPLATE/FOOTER/ENABLE_DISABLE';
const CHANGE_PAGE_MARGIN = 'EDIT_TEMPLATE/PAGE/CHANGE_MARGIN';
const ADD_TO_HISTORY = 'EDIT_TEMPLATE/HISTORY/ADD';
const ADD_TO_HISTORY_NEXT = 'EDIT_TEMPLATE/HISTORY/ADD_NEXT';
const ADD_TO_HISTORY_PREV = 'EDIT_TEMPLATE/HISTORY/ADD_PREV';
const UNDO = 'EDIT_TEMPLATE/HISTORY/UNDO';
const REDO = 'EDIT_TEMPLATE/HISTORY/REDO';
const SELECT_ELEMENT= 'EDIT_TEMPLATE/SELECT_ELEMENT'

export default {
    ENABLE_DISABLE_HEADER,
    CHANGE_HEADER_STYLE,
    ENABLE_DISABLE_FOOTER,
    CHANGE_FOOTER_STYLE,
    ADD_TO_HISTORY,
    ADD_TO_HISTORY_NEXT,
    ADD_TO_HISTORY_PREV,
    CHANGE_PAGE_MARGIN,
    SELECT_ELEMENT,
    UNDO,
    REDO
}