enum types {
	START_FETCHING_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/START_FETCHING',
	INIT_EDIT_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/INIT',
	END_FETCHING_TEMPLATE = 'EDIT_TEMPLATE/TEMPLATE/END_FETCHING',
	CHANGE_HEADER_STYLE = 'EDIT_TEMPLATE/HEADER/CHANGE_STYLE',
	ENABLE_DISABLE_HEADER = 'EDIT_TEMPLATE/HEADER/ENABLE_DISABLE',
	CHANGE_FOOTER_STYLE = 'EDIT_TEMPLATE/FOOTER/CHANGE_STYLE',
	ENABLE_DISABLE_FOOTER = 'EDIT_TEMPLATE/FOOTER/ENABLE_DISABLE',
	CHANGE_PAGE_MARGIN = 'EDIT_TEMPLATE/PAGE/CHANGE_MARGIN',
	SELECT_ELEMENT = 'EDIT_TEMPLATE/SELECT_ELEMENT',
	ADD_TO_HISTORY = 'EDIT_TEMPLATE/HISTORY/ADD',
	ADD_TO_HISTORY_NEXT = 'EDIT_TEMPLATE/HISTORY/ADD_NEXT',
	ADD_TO_HISTORY_PREV = 'EDIT_TEMPLATE/HISTORY/ADD_PREV',
	UNDO = 'EDIT_TEMPLATE/HISTORY/UNDO',
	REDO = 'EDIT_TEMPLATE/HISTORY/REDO',
}

export default types
